services:
  db:
    image: mariadb:11.4
    container_name: filmapi-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: filmapi_db
      MYSQL_USER: filmapi_user
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - filmapi_mariadb_data:/var/lib/mysql

volumes:
  filmapi_mariadb_data:
