// <auto-generated />
using System;
using FilmAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilmAPI.Migrations
{
    [DbContext(typeof(FilmDbContext))]
    [Migration("20260419152609_AddStripeCheckoutFieldsToOrdine")]
    partial class AddStripeCheckoutFieldsToOrdine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FilmAPI.Model.Biglietto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BarcodeValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CodiceBiglietto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("OrdineId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrezzoBase")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PrezzoTotale")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("SalaPostoId")
                        .HasColumnType("int");

                    b.Property<int>("ShowId")
                        .HasColumnType("int");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.Property<decimal>("Supplemento")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ValidatoAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ValidatoCinemaId")
                        .HasColumnType("int");

                    b.Property<int?>("ValidatoDaUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodiceBiglietto")
                        .IsUnique();

                    b.HasIndex("OrdineId");

                    b.HasIndex("SalaPostoId");

                    b.HasIndex("UserId");

                    b.HasIndex("ValidatoCinemaId");

                    b.HasIndex("ValidatoDaUserId");

                    b.HasIndex("ShowId", "SalaPostoId")
                        .IsUnique();

                    b.ToTable("Biglietti");
                });

            modelBuilder.Entity("FilmAPI.Model.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("FilmAPI.Model.Cinema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Citta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CodiceLocale")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<double?>("Latitudine")
                        .HasColumnType("double");

                    b.Property<double?>("Longitudine")
                        .HasColumnType("double");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Cinemas");
                });

            modelBuilder.Entity("FilmAPI.Model.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CastText")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("CopertinaPath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("DataProduzione")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly?>("DataRilascio")
                        .HasColumnType("date");

                    b.Property<string>("DescrizioneLunga")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("Durata")
                        .HasColumnType("int");

                    b.Property<string>("FilmatoPath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("RegistaId")
                        .HasColumnType("int");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("RegistaId");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("FilmAPI.Model.FilmCategoria", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.HasKey("FilmId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("FilmCategorie");
                });

            modelBuilder.Entity("FilmAPI.Model.MovimentoCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CinemaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Importo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("OperatoreUserId")
                        .HasColumnType("int");

                    b.Property<int?>("OrdineId")
                        .HasColumnType("int");

                    b.Property<decimal>("SaldoPost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SaldoPre")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.HasIndex("OperatoreUserId");

                    b.HasIndex("OrdineId");

                    b.HasIndex("UserId");

                    b.ToTable("MovimentiCredito");
                });

            modelBuilder.Entity("FilmAPI.Model.Ordine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CheckoutCompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CheckoutExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<string>("CodiceOrdine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("CreditoRiservato")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<string>("HoldToken")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<decimal>("ImportoCarta")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ImportoCredito")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("LastPaymentError")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("NumeroBiglietti")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.Property<int>("ShowId")
                        .HasColumnType("int");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.Property<string>("StripeCheckoutSessionId")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("TicketEmailLastError")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("TicketEmailSentAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TotaleLordo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.HasIndex("CodiceOrdine")
                        .IsUnique();

                    b.HasIndex("FilmId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("SalaId");

                    b.HasIndex("ShowId");

                    b.HasIndex("UserId");

                    b.ToTable("Ordini");
                });

            modelBuilder.Entity("FilmAPI.Model.Prenotazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPrenotazione")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("NumeroPosti")
                        .HasColumnType("int");

                    b.Property<int>("ProiezioneId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProiezioneId");

                    b.HasIndex("UserId");

                    b.ToTable("Prenotazioni");
                });

            modelBuilder.Entity("FilmAPI.Model.Proiezione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ora")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("CinemaId", "FilmId", "Data", "Ora")
                        .IsUnique();

                    b.ToTable("Proiezioni");
                });

            modelBuilder.Entity("FilmAPI.Model.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "DeviceId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("FilmAPI.Model.Regista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nazionalita")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Registi");
                });

            modelBuilder.Entity("FilmAPI.Model.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAttiva")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("NumeroProgressivo")
                        .HasColumnType("int");

                    b.Property<decimal>("Supplemento")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TipoSala")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId", "NumeroProgressivo")
                        .IsUnique();

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("FilmAPI.Model.SalaPosto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Fila")
                        .HasColumnType("int");

                    b.Property<bool>("IsAttivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsWheelchair")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int?>("PosX")
                        .HasColumnType("int");

                    b.Property<int?>("PosY")
                        .HasColumnType("int");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.Property<string>("Settore")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("SalaId", "Settore", "Fila", "Numero")
                        .IsUnique();

                    b.ToTable("SalaPosti");
                });

            modelBuilder.Entity("FilmAPI.Model.Show", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<int>("DurataMinutiSnapshot")
                        .HasColumnType("int");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrezzoBase")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("SupplementoSala")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("SalaId");

                    b.HasIndex("CinemaId", "SalaId", "StartAtUtc")
                        .IsUnique();

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("FilmAPI.Model.ShowPostoStato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HoldToken")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int?>("OrdineId")
                        .HasColumnType("int");

                    b.Property<int>("SalaPostoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScadeAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ShowId")
                        .HasColumnType("int");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HoldToken");

                    b.HasIndex("OrdineId");

                    b.HasIndex("SalaPostoId");

                    b.HasIndex("ScadeAtUtc");

                    b.HasIndex("UserId");

                    b.HasIndex("ShowId", "SalaPostoId")
                        .IsUnique();

                    b.ToTable("ShowPostiStato");
                });

            modelBuilder.Entity("FilmAPI.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CinemaPreferitoId")
                        .HasColumnType("int");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("CreditoResiduo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("DataRegistrazione")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Ruolo")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CinemaPreferitoId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FilmAPI.Model.Biglietto", b =>
                {
                    b.HasOne("FilmAPI.Model.Ordine", "Ordine")
                        .WithMany("Biglietti")
                        .HasForeignKey("OrdineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.SalaPosto", "SalaPosto")
                        .WithMany()
                        .HasForeignKey("SalaPostoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Show", "Show")
                        .WithMany("Biglietti")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.User", "User")
                        .WithMany("Biglietti")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Cinema", "ValidatoCinema")
                        .WithMany()
                        .HasForeignKey("ValidatoCinemaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FilmAPI.Model.User", "ValidatoDaUser")
                        .WithMany()
                        .HasForeignKey("ValidatoDaUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ordine");

                    b.Navigation("SalaPosto");

                    b.Navigation("Show");

                    b.Navigation("User");

                    b.Navigation("ValidatoCinema");

                    b.Navigation("ValidatoDaUser");
                });

            modelBuilder.Entity("FilmAPI.Model.Film", b =>
                {
                    b.HasOne("FilmAPI.Model.Regista", "Regista")
                        .WithMany("Films")
                        .HasForeignKey("RegistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Regista");
                });

            modelBuilder.Entity("FilmAPI.Model.FilmCategoria", b =>
                {
                    b.HasOne("FilmAPI.Model.Categoria", "Categoria")
                        .WithMany("FilmCategorie")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Film", "Film")
                        .WithMany("FilmCategorie")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Film");
                });

            modelBuilder.Entity("FilmAPI.Model.MovimentoCredito", b =>
                {
                    b.HasOne("FilmAPI.Model.Cinema", "Cinema")
                        .WithMany()
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FilmAPI.Model.User", "OperatoreUser")
                        .WithMany()
                        .HasForeignKey("OperatoreUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FilmAPI.Model.Ordine", "Ordine")
                        .WithMany()
                        .HasForeignKey("OrdineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FilmAPI.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("OperatoreUser");

                    b.Navigation("Ordine");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FilmAPI.Model.Ordine", b =>
                {
                    b.HasOne("FilmAPI.Model.Cinema", "Cinema")
                        .WithMany()
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Film", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Sala", "Sala")
                        .WithMany()
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Show", "Show")
                        .WithMany("Ordini")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.User", "User")
                        .WithMany("Ordini")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("Film");

                    b.Navigation("Sala");

                    b.Navigation("Show");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FilmAPI.Model.Prenotazione", b =>
                {
                    b.HasOne("FilmAPI.Model.Proiezione", "Proiezione")
                        .WithMany()
                        .HasForeignKey("ProiezioneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.User", "User")
                        .WithMany("Prenotazioni")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proiezione");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FilmAPI.Model.Proiezione", b =>
                {
                    b.HasOne("FilmAPI.Model.Cinema", "Cinema")
                        .WithMany("Proiezioni")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Film", "Film")
                        .WithMany("Proiezioni")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("Film");
                });

            modelBuilder.Entity("FilmAPI.Model.RefreshToken", b =>
                {
                    b.HasOne("FilmAPI.Model.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FilmAPI.Model.Sala", b =>
                {
                    b.HasOne("FilmAPI.Model.Cinema", "Cinema")
                        .WithMany("Sale")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("FilmAPI.Model.SalaPosto", b =>
                {
                    b.HasOne("FilmAPI.Model.Sala", "Sala")
                        .WithMany("Posti")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("FilmAPI.Model.Show", b =>
                {
                    b.HasOne("FilmAPI.Model.Cinema", "Cinema")
                        .WithMany()
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Film", "Film")
                        .WithMany("Shows")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Sala", "Sala")
                        .WithMany("Shows")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("Film");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("FilmAPI.Model.ShowPostoStato", b =>
                {
                    b.HasOne("FilmAPI.Model.Ordine", "Ordine")
                        .WithMany()
                        .HasForeignKey("OrdineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FilmAPI.Model.SalaPosto", "SalaPosto")
                        .WithMany()
                        .HasForeignKey("SalaPostoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Show", "Show")
                        .WithMany("PostiStato")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ordine");

                    b.Navigation("SalaPosto");

                    b.Navigation("Show");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FilmAPI.Model.User", b =>
                {
                    b.HasOne("FilmAPI.Model.Cinema", "CinemaPreferito")
                        .WithMany()
                        .HasForeignKey("CinemaPreferitoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CinemaPreferito");
                });

            modelBuilder.Entity("FilmAPI.Model.Categoria", b =>
                {
                    b.Navigation("FilmCategorie");
                });

            modelBuilder.Entity("FilmAPI.Model.Cinema", b =>
                {
                    b.Navigation("Proiezioni");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("FilmAPI.Model.Film", b =>
                {
                    b.Navigation("FilmCategorie");

                    b.Navigation("Proiezioni");

                    b.Navigation("Shows");
                });

            modelBuilder.Entity("FilmAPI.Model.Ordine", b =>
                {
                    b.Navigation("Biglietti");
                });

            modelBuilder.Entity("FilmAPI.Model.Regista", b =>
                {
                    b.Navigation("Films");
                });

            modelBuilder.Entity("FilmAPI.Model.Sala", b =>
                {
                    b.Navigation("Posti");

                    b.Navigation("Shows");
                });

            modelBuilder.Entity("FilmAPI.Model.Show", b =>
                {
                    b.Navigation("Biglietti");

                    b.Navigation("Ordini");

                    b.Navigation("PostiStato");
                });

            modelBuilder.Entity("FilmAPI.Model.User", b =>
                {
                    b.Navigation("Biglietti");

                    b.Navigation("Ordini");

                    b.Navigation("Prenotazioni");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
